#!/bin/sh
#
# Copyright (C) 2024 Gerard Roche
#
# This file is part of This program.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with This program.  If not, see <https://www.gnu.org/licenses/>.

set -e
unset CDPATH
unset IFS

if [ ! -f "$PWD/pre-commit" ]; then
    echo >&2 "Please run installer from project root."
    exit 1
fi

[ -d ~/.githooks ] || mkdir -p ~/.githooks

git config --global core.hooksPath ~/.githooks

if [ ! -f ~/.githooks/pre-commit-php ]; then
    ln -s "$PWD/pre-commit" ~/.githooks/pre-commit-php
fi

if [ ! -f ~/.githooks/pre-commit ]; then
    cat > ~/.githooks/pre-commit <<'EOF'
#!/bin/sh
set -e
unset CDPATH
unset IFS

if [ -f ~/.githooks/pre-commit-php ]; then
    exec ~/.githooks/pre-commit-php
fi

if [ -f .git/hooks/pre-commit ]; then
    exec .git/hooks/pre-commit
fi
EOF
fi

echo "done!"
